name: CI
on: [push]
env:
    QT_QPA_PLATFORM: offscreen
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U PyQt5 pytest pathlib2 pytest-asyncio pytest-qt pytest-cov aiohttp codecov
      - name: Install
        run: pip install -e ./
      - name: Setup os
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update -q -y
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libgl1-mesa-glx xserver-xorg xvfb gdb
      - name: Run tests
        run: pytest -v tests --cov asyncqtpy --cov-report xml --asyncio-mode auto
      - name: Coverage
        run: codecov
  check-code:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U isort flake8 black mypy pytest pathlib2 pytest-cov codecov
      - name: Run checks
        run: |
            isort --profile=black --check --diff ./
            black --check --diff ./
            flake8 --ignore=E501,W503 ./
            mypy asyncqtpy --ignore-missing-imports
